---
title: "About"
---

Hi, I'm Kyle Arean-Raines. Thanks for visiting my blog! I write about physics and math concepts that interest me
and that I want to dive deeper into to refresh my memory and understand better.  

I'm a Software Engineer by day, working to solve challenging engineering problems at scale at Toast. 
Before that I studied chemical engineering at the University of Rochester and got my master's in materials science 
at Carnegie Mellon.

I also used to be active on Physics Stack Exchange, though I haven't posted in a while. You can find my profile 
[here](https://physics.stackexchange.com/users/82256/kyle-arean-raines).

Posts range from intro-level, with minimal prerequisites and an emphasis on intuition, to advanced with lots of
math required for a proper understanding of the physics. Categories and difficulty badges are on the main page. 
If you want new posts by email, there's a subscribe form on every page.

The code and text for this blog are open at github.com/kareanra/physics-blog. 
Feedback, corrections, and interesting problems are welcome at kyle.areanraines@gmail.com.

The source for the whole site, including the physics module, is on
[GitHub](https://github.com/kareanra/physics-blog). Claude helped me out quite a bit with initial project setup
and gaining familiarity with Quarto. All the prose and derivations are mine.
